### ISSUE TITLE
Trigger a push through http?

### ISSUE THREAD

**Issue by wibeasley** [IUREDCap/redcap-etl#12]
I loved the project and presentation yesterday.  I liked how the pushes can be scheduled or manually initiated by clicking a button.

We frequently use R to get REDCap data into sql server and then a second R operation to pull the sql server data again (after joining with other sources) into R for analysis.  

It might be nice to substitute your tool for the first hop.  But I'd need to specify/trigger when it runs.  Somedays it might run fifty times, but then not again for another two weeks.  

Is there a way to programmatically trigger a push from outside the REDCap server?

**Comment by mullen2** [comment]
@wibeasley Thanks!

You could run the standalone REDCap-ETL program (this is the repo for that; the external module repo is at https://github.com/IUREDCap/redcap-etl-module/). If you install (standalone) REDCap-ETL on the server where you are running your R, you could execute (in the top-level directory of REDCap-ETL):

`./bin/redcap_etl.php <config-file>`

whenever you want to run your ETL process. However, REDCap-ETL still does not support SQL Server.
