### ISSUE TITLE
add to "redcap-tools" list 

### ISSUE THREAD

**Issue by wibeasley** [IUREDCap/redcap-etl#27]
@aarenson, @mullen2, and everyone else on this project: I'm sorry I won't get to see an updated poster about redcap-etl this year at REDCapCon.

Like PHPCap, I think this tool would fit well on the [redcap-tools list](http://redcap-tools.github.io/projects/).  If you want it included, please [create an issue](https://github.com/redcap-tools/redcap-tools.github.io/issues) and tell us:

* a one or two sentence description (that ideally distinguishes it from the others -which shouldn't be hard for this unique project)
* the language(s) used
* a link to the documentation, if desired
* a link to the version badge, if desired

**Comment by mullen2** [comment]
@wibeasley Thanks for contacting us. I don't see REDCap-ETL fitting well into the Libraries section where PHPCap is. Although REDCap-ETL could be used as a library, we have not been promoting it in that way and have not documented it for that use. Also, as a library, REDCap-ETL is far less general than PHPCap and most or all of the other libraries listed. If you had an Applications section, I think it would fit well there. Would you be willing to add a new Applications section?

**Comment by wibeasley** [comment]
Cool.  Will you please


- [ ] modify your REDCap-ETL description to reflect what you want
    https://github.com/redcap-tools/redcap-tools.github.io/blob/dev/_data/applications.yml

- [ ] gimme your best shot at the descriptions for the new "applications" section.  I included the EM repo so you wouldn't be so lonely.

    https://github.com/redcap-tools/redcap-tools.github.io/blob/dev/projects.md#applications

Notice both of these are on the dev branch.

**Comment by mullen2** [comment]
A pull request (https://github.com/redcap-tools/redcap-tools.github.io/pull/50) was made for this, but not accepted.
