### ISSUE TITLE
Problem with radio buttons if database field for them defined as int

### ISSUE THREAD

**Issue by mullen2** [IUREDCap/redcap-etl#31]
For SQL Server, and possibly other database, if you define the database field in the transformation rules as type int for a REDCap radio field, null gets generated for zero values. Note that the rules generator specifies type varchar(255) for these fields, because, in general, a radio field's values can have letters in them.

**Comment by jasonhoule** [comment]
Thanks for submitting this issue @mullen2. I was able to patch this in our REDCap instance and it is now working as expected. I have submitted pr #32 as a fix.
