### ISSUE TITLE
Creation of redcap_metadata table can generate SQL insert with too many row values 

### ISSUE THREAD

**Issue by mullen2** [IUREDCap/redcap-etl#35]
If the number of fields in a REDCap project being used is large, the creation of the redcap_metadata table may generate an SQL insert statement with so many row values that it causes an error. For example, SQL Server limits the number of row values in an insert to 1,000.

**Comment by jkixj** [comment]
We are also having this problem. The specific error message is:

> Database error while trying to insert values into table "[redcap_etl_lookups]": SQLSTATE[42000]: [Microsoft][ODBC Driver 18 for SQL Server][SQL Server]The number of row value expressions in the INSERT statement exceeds the maximum allowed number of 1000 row values.

We are using redcap-etl version 2.3.0, PHP version 8.1 and SQL driver version 5.10.

Any clues how to fix or work around this are appreciated.

**Comment by mullen2** [comment]
It looks like your problem is for the lookup table (and not the redcap_metadata table as reported in the original issue). Can you change your configuration to turn off creation of the lookup table (set create_lookup_table = 0), or is this table critical for what you are doing? (See https://github.com/IUREDCap/redcap-etl/blob/master/docs/ConfigurationGuide.md for more information on configuration settings).

**Comment by jkixj** [comment]
> It looks like your problem is for the lookup table (and not the redcap_metadata table as reported in the original issue). Can you change your configuration to turn off creation of the lookup table (set create_lookup_table = 0), or is this table critical for what you are doing? (See https://github.com/IUREDCap/redcap-etl/blob/master/docs/ConfigurationGuide.md for more information on configuration settings).

Thank you. Turning that off does work.

We can use this a workaround, but the registry has a lot of lookup values, so it would be great if it would work with it left on.

**Comment by mullen2** [comment]
By default, REDCap-ETL should be generating multiple-choice response values and labels in the databases tables it generates, so you should be able to get the labels without the lookup table.

**Comment by mullen2** [comment]
I just released version 2.3.1, which should fix this issue.

Originally, REDCap-ETL only stored the multiple-choice response values in the tables it generated, and views were constructed from those tables that contained the labels instead of the values. Recently, the ability to store both the values in labels in the tables that are generated was added.

**Comment by mullen2** [comment]
@jkixj If you could provide information on what you use the lookup table for, that would be helpful. We have thought about removing this feature, especially now that label fields have been implemented, but we don't want to cause problems for users if there is still a good use case for the lookup table.

**Comment by mullen2** [comment]
Issues have been addressed.
