### ISSUE TITLE
Lookup table is not created

### ISSUE THREAD

**Issue by cepeti** [IUREDCap/redcap-etl#36]
Tried running ETL for a project using a simple test, making only one table with a few columns. It even says it created a lookup table, but it doesn't.

![image](https://user-images.githubusercontent.com/115028604/199770815-751aa113-8df6-4f47-b89e-e247cda8c136.png)

I configured it to create it in my config.ini:
![image](https://user-images.githubusercontent.com/115028604/199771156-bf4a1a21-9449-4c3d-a1a9-858082d297c6.png)

But after i run ETL, the lookup table is not there
![image](https://user-images.githubusercontent.com/115028604/199771329-965895d7-2e38-43d3-bce2-15eaae43d4ed.png)

Here's the log after the first run. It says the lookup table is created:
![image](https://user-images.githubusercontent.com/115028604/199771837-720e0b92-c932-4110-878a-968f4764ce0e.png)

**Comment by cepeti** [comment]
Yes i'm using many fields of multiple choice and they are in used in the transformation file (select and radio types on redcap)

**Comment by mullen2** [comment]
@cepeti Thanks for the feedback and detailed information. I am looking into this.

**Comment by mullen2** [comment]
@cepeti Thanks for finding this. It should now be fixed in version 2.2.1, which was just released.
