### ISSUE TITLE
Support for php 8+?

### ISSUE THREAD

**Issue by cepeti** [IUREDCap/redcap-etl#37]
In the installation requirements section it states "PHP 5.6+ or 7+...". From the way it's written i'm not sure if PHP 8 is supported or if it's only up to 7.x.

I have a project that will need php 8 and i wouldn't want to use separate servers for the task. Is there any risk in using php 8 for redcap-etl?

**Comment by aarenson** [comment]
Jim can give a more definitive answer, but I don't think we've fully tested redcap-etl with PHP8 yet.

**Comment by mullen2** [comment]
REDCap-ETL was tested with PHP 8.1 and changes where made to address the known issues at that time: https://github.com/IUREDCap/redcap-etl-module/releases/tag/2.1.4

**Comment by mullen2** [comment]
I will update the installation guide.
