### ISSUE TITLE
Unexpected UI for manual run of an embedded server that only allows CSV downloads

### ISSUE THREAD

**Issue by aarenson** [IUREDCap/redcap-etl#38]
After configuring the embedded server to be CSV only and then going to a project and testing out a manual run of a configuration, I found it momentarily confusing that there was a dropdown list to choose 'Export data as CSV zip file'.

In contrast, for another defined server there is no dropdown list at all.

I expect that the reason for this discrepancy is that for remote servers there never can be more than one choice, while for the embedded server there could be a choice.

I wonder if a less confusing interface might be to always have the drop down list, whether using the embedded server or another server, and always have the two possible choices (remote execution and CSV file), but to gray out the available choice if only one choice is available.

Alternatively, if there is only once choice, perhaps replace the dropdown with text noting what will happen (remote execution, CSV file).

**Comment by mullen2** [comment]
Thanks for the feedback. I'll look into this further. I think something along the lines of your alternate suggestion sounds good to me. I think it can be frustrating to see grayed out options, especially when there is no possible way to activate them, which would be the case for CSV download for remote servers. Or, I could possibly improve the help. Currently, the ETL server shows up as select even if there is only one choice, but this is explained in the help for the page.

I have not heard of anyone outside of IU using the remote server option, so the server specification inconsistency may be an issue only at IU.

**Comment by mullen2** [comment]
Note: this issue applies to the REDCap-ETL external module (and not the REDCap-ETL application) and should have been posted to its GitHub repository: https://github.com/IUREDCap/redcap-etl-module/

**Comment by mullen2** [comment]
I moved this issue to the repo for the REDCap-ETL Module.
