### ISSUE TITLE
Filter by Records Created or Modified in Timespan

### ISSUE THREAD

**Issue by cepeti** [IUREDCap/redcap-etl#39]
Is it possible to add to the config file, parameters for dateRangeBegin and dateRangeEnd so we can use the created/modified timespan alongside the filter logic?

(Image with the feature in the API Playground)
![image](https://user-images.githubusercontent.com/115028604/222472130-a17f264a-b75e-42b4-97fc-1a1037e6ea56.png)

If that's not possible, is there any way to achieve the same thing only with the extract filter logic? I don't know how to access the modified/created timestamp since it's not a REDCap variable.

**Comment by aarenson** [comment]
Given that REDCap-ETL completely removes and replaces data whenever it runs, are you looking solely to create a potentially reduced dataset when loading, or do you have in mind some sort of synchronization in which REDCap-ETL would only add/update rows/data when loading, rather than completely replacing all existing data?

**Comment by cepeti** [comment]
I extract the data to one table with ETL and select only the rows i care about to another table (one that ETL doesn't write on) with the post script so it'll make it much lighter to filter all the unchanged data.

**Comment by cepeti** [comment]
I made a few tests to increase the amount of data and eventually redcap-etl hits redcap's rate limit. This project will run for a long time (over 2 years) and it'll eventually get very big.

I don't want to increase the global rate limit for that so that'll force me to make computed variables for each form that save the current timestamp whenever someone saves a form. Then i can filter the modification timestamp through the extract filter logic, but it's redundant since REDCap already has modification timestamp that i could use.

**Comment by mullen2** [comment]
@cepeti Thanks for the information. I cannot remember hitting the rate limit, or someone else reporting that as an issue. I tried a project with 10,000 records and set the batch size to 1 to generate the maximum number of requests to REDCap and still did not hit my rate limit (set at 2,400 requests per minute per IP address). Could you please tell me what your rate limit and REDCap-ETL batch size are set to, and what kind of project (number of rows and fields) is exceeding it?

**Comment by cepeti** [comment]
Oh i forgot about the batch size, i should probably increase that to reduce the amount of requests per minute. I'll run a couple tests to find the optimal value.

My batch size was at one, as the default value, and REDCap's rate limit was at 600 (which i don't remember ever changing so i'll guess it's the default as well) and i increased it to 1000 to solve it for now. But i don't imagine any other normal use case would require that much. Unfortunately REDCap doesn't have a "white list" feature to allow a lower request rate.

This project has over 250 fields (9 instruments, a few optional but also some are repeating instruments) and there are over 2500 records right now. My request (the one that hit the max request rate) filtered about 1100 of them, and we expect to hit about 50.000 records eventually.

Aside from having REDCap-ETL this server is also set as a Data Entry Trigger in the project, so that adds a few more requests but i think i was just at the very limit since i tried the same extract logic in another machine the day before and it didn't get blocked.

**Comment by cepeti** [comment]
But regardless of this max request rate issue, using REDCap's native modify / create timestamp would allow for a much more efficient filter on the data.

**Comment by mullen2** [comment]
Generally, our users run the REDCap-ETL process overnight, once per day. REDCap-ETL is not intended for real time or frequent data extractions.

Based on tests I have done, I think it would be reasonable to run REDCap-ETL once per night on a project of the size you indicate yours will eventually reach (on our system at least). If you could test on your system specifically, that would be great. However, the batch size is critical. A small size, particularly 1, is going to GREATLY increase the run time. I have also found that a size that is too large can be counter productive. It can increase the memory usage substantially without improving the time that much, or even decreasing it slightly. Also, if the batch size is too large, you may run out of memory. I think the default batch size of 100 is a good starting point, and then you could start increasing it from there if necessary in increments of 50 until you are no longer seeing a significant improvement in run time performance or you run out of memory.

When the date range option was added to the REDCap API, I looked into a way to support incremental updates in REDCap-ETL, but found there were too many problems, including:

- **Records imported at project creation.** Records that are imported at project creation time in REDCap are not returned when date ranges are used.
- **Record deletions.** Using the date range will not pick up records that have been deleted in REDCap. So you will have records in your incrementally updated table that should not be there.
- **ETL transformation rules changes.** Changes in the transformation rules could lead to inconsistencies between the current and previously saved data.
- **Data dictionary changes.** Changes in the REDCap data dictionary (e.g., adding/deleting/renaming fields) can lead to inconsistencies between the current and previously saved data.

**Comment by cepeti** [comment]
Thank you for this answer.

Since i don't have any problem about keeping the deleted records (these cases are exceptions and have to be handed manually anyway) i still intend to create computed variables with a timestamp for the most recent change in the main instrument. Do you think i'll have any of this problems, like inconsistencies in the Data dictionary for example?

No record was imported at project creation and i don't intend to change anything in the transformation rules. If i pull different sets of data using the extraction logic, could that change the Data Dictionary or the lookup table?

**Comment by mullen2** [comment]
By data dictionary, I am referring to REDCap's data dictionary, which would change if you change the design of your project in REDCap (e.g., add/delete/rename a field/variable, add new multiple-choice options, renumber multiple-choice options, add a new form). If you are certain you will never make such a change going forward, then this won't be an issue.

If you never change your REDCap data dictionary, the lookup table generated by REDCap-ETL should not be affected either. However, we are thinking of removing the lookup table. It is not supported in the REDCap-ETL external module, and it is no longer needed internally for generating the label views (which have been deprecated anyway). If you actually need the lookup table, please let us know what it is useful to you for. If someone can provide a reasonable use case for it, I think we would be inclined to keep it in.

Another issue not mentioned above is that changes to REDCap-ETL could have an effect on things. For example, I recently improved the field type generation for transformation rules auto-generation. If you were using the auto-generation option for the transformation rules, that would have lead to a difference in the field types of the saved database and REDCap-ETL generated database. If you hand-coded your transformation rules, or auto-generated them to a file once using the script provided for that, then it would not be an issue. In general, however, our working assumption is that people are re-generating the entire database each time REDCap-ETL is run, and we will make changes to REDCap-ETL going forward based on that assumption.

If it is feasible for you to recreate the database each time REDCap-ETL is run, I think that is the way to go. If you proceed with your incremental update plan, I am interested in hearing about any additional issues you run into that have not already been mentioned.

**Comment by cepeti** [comment]
I use the lookup table to reflect the changes on the data dictionary back into my other database. That way, the system can be managed only in REDCap.

I need each of the fields and options on their own table with an unique id so i can build the relationships for each model, so i can't just use the lookup table as it comes (since it combines all choices in one table). All i need is for REDCap-ETL to keep the value column consistent to the same options in each run.

I made the transformation rules manually, and make one table with all records and an extra one for a repeating instrument, with data for those records. Those tables are not used by the app i'm making so they can be overwritten at each run.

On the post script i update tables i have for each multiple choice fields pulling from the lookup table. With an insert in MySQL, i use the "ON DUPLICATE KEY UPDATE" statement to make sure i grab any new items / label changes from the lookup table to each table containing the options for every multiple choice field i need. I have one table for each multiple choice field and i use the "value" field as the ID for each choice to make sure each option gets an unique ID no matter what changes in the lookup table.

Then i insert to a whole new table combining the records extracted (defined by the transformation rules), with the IDs of each multiple choice fields, and i also use the "ON DUPLICATE KEY UPDATE" statement to make sure i update changes on each record (using REDCap's id variable as the identifier for this) while also adding new records that didn't exist on the prior run.

This new table has new unique ids, and i compare them to the extracted record using REDCap's ID variable which is also unique and consistent through every run of REDCap-ETL.

I could manage deletions with a join but i rather do it manually as it's better to make sure and delete each record on both systems than risk losing data.

I'm still building the application, and it's supposed to be done by May. I did many test runs to make sure it works, and now by changing the batch size it's running in a really good time. I'm able to fetch way more than enough data than we expect to have updated in a day in REDCap, all i need is a way to make sure i only grab recently updated records so i can keep them in sync ~ every 1 - 2 hours, instead of once a day.

**Comment by mullen2** [comment]
I don't fully understand your use of the lookup table, but the following information may be helpful. The lookup table only provides information on multiple-choice fields, so it will not reflect all changes to the data dictionary. REDCap-ETL also generates the redcap_metadata table, which provides information about the mapping between database fields and REDCap fields.

Initially, REDCap-ETL only generated multiple-choice values in tables, and then it created views for each of those tables that contained the multiple-choice labels instead (called "label views"). The initial implementation of label views used the lookup table to construct the views. However, this implementation was specific to MySQL, so once additional database systems were added, the implementation was changed. The new implementation does not use the lookup table (so we no longer need it internally).

The label views have some problems, so label fields were added to the database tables generated by REDCap-ETL. The tables now contain both the multiple-choice values and labels. Label views have been deprecated and the hope is to remove them in a future version.

**Comment by cepeti** [comment]
All i need is the multiple choice options. New fields don't need to be added as their likely not going to be needed so if it ever comes to it i'll add it in the transformation rules. 

With the lookup table i can create individual tables for each multiple choice option, and then i can link the id to each choice as the foreign id in the record table, using the "value" column as their id. That's so i can store id values but also access their redcap labels so i can show this data in a meaningful way for users. I need individual tables for each multiple choice options since i'll create many filters, so it'll be faster to filter through each multiple choice field in their own table.

For example, for the the insurances field.

![lookup](https://user-images.githubusercontent.com/115028604/225047074-915397b3-3729-4548-82b7-d14c7aca82a9.png)

when new choices are added, or when their labels are changed, they're updated in my app. But the metadata table doesn't give me info about the choices, only about the fields, that's why i use the lookup table.

Here's the post script with some of the transformations i use. I add / update the insurances in it's own table and do the same with the records (while assigning the id from each multiple choice field).

![image](https://user-images.githubusercontent.com/115028604/225049639-67e49e89-8b6b-4f2d-a89d-5d9b1654f4fe.png)

![image](https://user-images.githubusercontent.com/115028604/225051007-3f3cc8ff-0899-42f3-b9b7-e5aa0c4fa2a1.png)

**Comment by mullen2** [comment]
@cepeti Thanks for the additional information.

REDCap-ETL by default generates multiple-choice values and labels in tables. For example:

![image](https://user-images.githubusercontent.com/25109733/225402234-9f7b9fa3-889b-4371-a2c8-e46bd36b0021.png)

Is there a reason why you can't use the label fields generated in the tables by REDCap-ETL?

**Comment by cepeti** [comment]
@mullen2 Thank you for your suggestions.

Due to the amount of data we'll have in this project i want to optimize storage and search time when filtering / sorting through these options. I'm currently testing for around 100.000 records and i had to establish some limits when filtering a list of records as it is. Storing all labels instead of a tiny int id from each multiple choice on all records would slow down those operations and increase storage.

**Comment by mullen2** [comment]
OK. Thanks for the additional information. It's good to get feedback about how people are using REDCap-ETL.
