### ISSUE TITLE
blank option is visible for the api user dropdown

### ISSUE THREAD

**Issue by tranpl** [IUREDCap/redcap-etl#41]
Only 1 API user is added, however multiple options shown and is not a real value. Remove or do not display this non value option?

![image](https://github.com/IUREDCap/redcap-etl/assets/4207355/68ac8347-4620-45bd-9558-4cde8d9b7808)

REDCap 14.1.4
REDCap ETL Module 2.3.9

**Comment by aarenson** [comment]
I think the blank option is useful.

Maybe the API token to be used hasn't been created yet, but one and only one other person already has an API token. I don't want that other token to be used by default.

**Comment by tranpl** [comment]
I think that makes sense. I was a little confused when I haven't seen the interface for so long to check/reconfigure something; it looked out of place =)
